### ISSUE TITLE
Scan and all dependend functions do not work in Windows

### ISSUE THREAD

**Issue by DarkPhily** [byReqz/go-ask-password#1]
When using your library in Windows, it's just returning "unprintable character entered" without a chance to enter any thing.

If I print r before your `!unicode.IsPrint(r)` I get the value 0.
Not quite sure why Windows adds the NULL character.
It's reproduceable with Powershell and CMD

I would suggest to check `if len(buff) == 0 && r == 0`

**Comment by byReqz** [comment]
#2 allows generally disabling the unprintable character error but should now also just drop null inputs as those arent necessary when going through the tty. Please check if this solves the issue.
